-- 사번 입력으로 급여를 인상하는 프로시저
SELECT * FROM EMP WHERE EMPNO = 7900;

-- EMPNO에 해당하는 사원의 급여를 10% 인상하는 프로시저 생성
CREATE OR REPLACE PROCEDURE UP_SAL2
(
	V_EMPNO EMP.EMPNO%TYPE
)
IS
	CNT_EMP NUMBER(1,0);
BEGIN
	SELECT COUNT(*) INTO CNT_EMP
	  FROM EMP
	 WHERE EMPNO = V_EMPNO;

	IF CNT_EMP > 0 THEN
		UPDATE EMP SET
			SAL = SAL + (SAL * 0.1)
		WHERE EMPNO = V_EMPNO;
		DBMS_OUTPUT.PUT_LINE('업데이트 성공');
	ELSE
		DBMS_OUTPUT.PUT_LINE('업데이트 실패');
	END IF;
END UP_SAL2;
/

--프로시저 실행
CALL UP_SAL2(7900);

COMMIT;