-- 함수 실행
SELECT MAX_SAL(10) FROM DUAL;

SELECT * FROM EMP WHERE DEPTNO = 10;

--스칼라 서브쿼리
SELECT E.EMPNO, E.NAME, E.DEPTNO
	 , (SELECT DNAME FROM DEPT2 WHERE DCODE = E.DEPTNO) AS 부서명
	 , (SELECT AREA FROM DEPT2 WHERE DCODE = E.DEPTNO) AS 지역
  FROM EMP2 E;

-- 함수로 변경
SELECT E.EMPNO, E.NAME, E.DEPTNO
	 , GET_DNAME(E.DEPTNO) AS 부서명
	 , GET_AREA(E.DEPTNO) AS 지역
  FROM EMP2 E;

-- 조인으로 가능
SELECT E.EMPNO, E.NAME, E.DEPTNO, D.DNAME, D.AREA
  FROM EMP2 E, DEPT2 D
 WHERE E.DEPTNO = D.DCODE;

COMMIT;