-- TRIGGER 학습
-- DEPT테이블 복사 DEPT_BACKUP

CREATE TABLE DEPT_BACKUP
AS
	SELECT * FROM DEPT;

-- DEPT_BACKUP 테이블에 LOG_DATE 컬럼 추가
ALTER TABLE DEPT_BACKUP
  ADD(LOG_DATE DATE);

-- 트리거 작성
CREATE OR REPLACE TRIGGER TRG_DEPTBACK
AFTER INSERT OR UPDATE ON DEPT -- DEPT테이블 트리거 메뉴에 저장 확인
FOR EACH ROW
BEGIN
	IF INSERTING THEN -- DEPT테이블에 데이터가 추가되면
		INSERT INTO DEPT_BACKUP
		VALUES (:NEW.DEPTNO, :NEW.DNAME, :NEW.LOC, SYSDATE);
	ELSIF UPDATING THEN -- DEPT테이블에 데이터가 수정되면
--		UPDATE DEPT_BACKUP
--		   SET DNAME = :NEW.DNAME
--		     , LOC = :NEW.LOC
--		     , LOG_DATE = SYSDATE
--		 WHERE DEPTNO = :OLD.DEPTNO;
		INSERT INTO DEPT_BACKUP
		VALUES (:OLD.DEPTNO, :NEW.DNAME, :NEW.LOC, SYSDATE);
--	ELSIF DELETING THEN
--		DELETE FROM DEPT_BACKUP
--		 WHERE DEPTNO = :OLD.DEPTNO;
	END IF;
	
END;

-- 원본 확인
SELECT * FROM DEPT;

-- 백업테이블 확인
SELECT * FROM DEPT_BACKUP;

-- 삽입
INSERT INTO DEPT VALUES (50, 'R&D', 'SEOUL');

-- 수정 BOSTON에서 LOS ANGELES로 변경
UPDATE DEPT SET
	   LOC = 'Los Angeles'
 WHERE deptno = 40;

DELETE FROM DEPT WHERE DEPTNO = 50;

ROLLBACK;

COMMIT;