-- 교수 번호로 교수의 이름과 보너스를 출력하는 프로시저
CREATE OR REPLACE PROCEDURE PROFESSOR_INFO
(
	V_PROFNO PROFESSOR.PROFNO%TYPE
)
IS
	O_NAME PROFESSOR.NAME%TYPE;
	O_BONUS PROFESSOR.BONUS%TYPE;
BEGIN
	-- 1. 교수 테이블을 조회해서 컬럼값을 변수에 할당
	SELECT NAME, BONUS INTO O_NAME, O_BONUS
	  FROM PROFESSOR
	 WHERE V_PROFNO = PROFNO;
	
	-- 2. 보너스 값의 여부로 분기
	IF O_BONUS > 0 THEN
		DBMS_OUTPUT.PUT_LINE(O_NAME || ' 교수의 보너스는 ' || O_BONUS);
	ELSE
		DBMS_OUTPUT.PUT_LINE(O_NAME || ' 교수의 보너스는 없음');
	END IF;
END PROFESSOR_INFO;
