-- 1
SELECT EMAIL, MOBILE, NAMES, ADDR
  FROM MEMBERTBL;

-- 2
SELECT NAMES AS 도서명, AUTHOR AS 저자, ISBN, PRICE AS 정가
  FROM BOOKSTBL
 ORDER BY ISBN;

-- 3
SELECT M.NAMES AS 비대여자명, M.LEVELS AS 등급, M.ADDR AS 주소, R.RENTALDATE AS 대여일
  FROM MEMBERTBL M, RENTALTBL R
 WHERE M.IDX = R.MEMBERIDX(+)
   AND R.RENTALDATE IS NULL
 ORDER BY M.LEVELS;

-- 4
SELECT DECODE(D.NAMES, NULL, '--합계--', D.NAMES) AS 장르, TO_CHAR(SUM(B.PRICE), '9,999,999') || '원' AS 총합계금액
  FROM BOOKSTBL B, DIVTBL D
 WHERE B.DIVISION = D.DIVISION
 GROUP BY ROLLUP(D.NAMES);

COMMIT;