/*
 * VIEW
 * */
-- SYSDBA로 실행해야 함.
-- ROLE CONNECT, RESOURCE는 부여했지만, VIEW생성 권한 없음.
GRANT CREATE VIEW TO SAMPLEUSER;

--
SELECT * FROM EMP2;

-- 뷰 생성 쿼리 DDL
CREATE OR REPLACE VIEW V_EMP2
AS
	SELECT EMPNO, NAME, DEPTNO, TEL, POSITION, PEMPNO
	  FROM EMP2;

-- 뷰 삭제
-- 뷰로 SELECT
SELECT *
  FROM V_EMP2;

-- 뷰로 INSERT
-- 단, 뷰에 속하지 않는 컬럼 중 NOT NULL 조건이 있으면 데이터 삽입 불가
INSERT INTO V_EMP2 VALUES (20000219, 'TOM HALLAND', 1004, '051)627-9968', 'IT Programmer', 19960303);

-- NOT NULL인 DEPTNO컬럼 빼고 뷰 수정
CREATE OR REPLACE VIEW V_EMP2
AS
	SELECT EMPNO, NAME, TEL, POSITION, PEMPNO
	  FROM EMP2;

-- DEPTNO 컬럼이 NOT NULL인데 뷰에는 존재하지 않아 INSERT 불가
INSERT INTO V_EMP2 VALUES (20000229, 'ZEN DAIYA', '051)627-9968', 'IT Programmer', 19960303);

COMMIT;

-- CRUD 중 SELECT만 가능하게 만들려면
CREATE OR REPLACE VIEW V_EMP2
AS
	SELECT EMPNO, NAME, DEPTNO, TEL, POSITION, PEMPNO
	  FROM EMP2
WITH READ ONLY;

-- 삽입 불가
INSERT INTO V_EMP2 VALUES (20000221, 'TOM HALLAND', 1004, '051)627-9968', 'IT Programmer', 19960303);

-- 복합뷰, 조인 등으로 여러 테이블을 합쳐서 보여주는 뷰
-- 복합뷰는 INSERT, UPDATE, DELETE가 거의 불가
CREATE OR REPLACE VIEW V_EMP3
AS
	SELECT E.EMPNO, E.NAME, E.DEPTNO, D.DNAME
	  FROM EMP2 E, DEPT2 D
	 WHERE E.DEPTNO = D.DCODE;

-- 조회
SELECT * FROM V_EMP3;