-- P408
CREATE VIEW v_emp
AS
SELECT E.ENAME, D.DNAME
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO;

SELECT *
  FROM V_EMP;

-- P409
SELECT E.DEPTNO, D.DNAME, E.SAL
  FROM (SELECT DEPTNO, MAX(SAL) SAL
  		  FROM EMP
 		 GROUP BY DEPTNO) E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO;

COMMIT;

-- P420 EX1
CREATE VIEW V_PROF_DEPT2
AS
 SELECT P.PROFNO, P.NAME, D.DNAME
   FROM PROFESSOR P, DEPARTMENT D
  WHERE P.DEPTNO = D.DEPTNO;

COMMIT;

-- P420 EX2
SELECT D.DNAME, S.MAX_HEIGHT, S.MAX_WEIGHT
  FROM (SELECT DEPTNO1, MAX(HEIGHT) MAX_HEIGHT, MAX(WEIGHT) MAX_WEIGHT
  		  FROM STUDENT
 		 GROUP BY DEPTNO1) S, DEPARTMENT D
 WHERE S.DEPTNO1 = D.DEPTNO;

-- P420 EX3
SELECT D.DNAME, S1.MAX_HEIGHT, S2.NAME, S2.HEIGHT
  FROM (SELECT DEPTNO1, MAX(HEIGHT) MAX_HEIGHT
  		  FROM STUDENT
 		 GROUP BY DEPTNO1) S1, DEPARTMENT D, STUDENT S2
 WHERE S1.DEPTNO1 = D.DEPTNO
   AND S1.DEPTNO1 = S2.DEPTNO1
   AND S1.MAX_HEIGHT = S2.HEIGHT;

-- P421 EX4
SELECT * FROM STUDENT;



COMMIT;