-- P408
CREATE VIEW v_emp
AS
SELECT E.ENAME, D.DNAME
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO;

SELECT *
  FROM V_EMP;

-- P409
SELECT E.DEPTNO, D.DNAME, E.SAL
  FROM (SELECT DEPTNO, MAX(SAL) SAL
  		  FROM EMP
 		 GROUP BY DEPTNO) E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO;

COMMIT;

-- P420 EX1
CREATE VIEW V_PROF_DEPT2
AS
 SELECT P.PROFNO, P.NAME, D.DNAME
   FROM PROFESSOR P, DEPARTMENT D
  WHERE P.DEPTNO = D.DEPTNO;

COMMIT;

-- P420 EX2
SELECT D.DNAME, S.MAX_HEIGHT, S.MAX_WEIGHT
  FROM (SELECT DEPTNO1, MAX(HEIGHT) MAX_HEIGHT, MAX(WEIGHT) MAX_WEIGHT
  		  FROM STUDENT
 		 GROUP BY DEPTNO1) S, DEPARTMENT D
 WHERE S.DEPTNO1 = D.DEPTNO;

-- P420 EX3
SELECT D.DNAME, S1.MAX_HEIGHT, S2.NAME, S2.HEIGHT
  FROM (SELECT DEPTNO1, MAX(HEIGHT) MAX_HEIGHT
  		  FROM STUDENT
 		 GROUP BY DEPTNO1) S1, DEPARTMENT D, STUDENT S2
 WHERE S1.DEPTNO1 = D.DEPTNO
   AND S1.DEPTNO1 = S2.DEPTNO1
   AND S1.MAX_HEIGHT = S2.HEIGHT;

-- P421 EX4
SELECT S1.GRADE, S1.NAME, S1.HEIGHT, S2.AVG_HEIGHT
  FROM STUDENT S1, (SELECT GRADE, AVG(HEIGHT) AVG_HEIGHT
  					  FROM STUDENT
 					 GROUP BY GRADE
 					 ORDER BY GRADE) S2
 WHERE S1.GRADE = S2.GRADE
   AND S1.HEIGHT > S2.AVG_HEIGHT
 ORDER BY GRADE
 
-- P421 EX5
SELECT *
  FROM (SELECT DENSE_RANK() OVER (ORDER BY PAY DESC) AS RANKING, NAME, PAY
  		  FROM PROFESSOR)
 WHERE RANKING <= 5;

-- P422 EX6
SELECT inTbl.NUM, intbl.profno, intbl.name, intbl.pay, sum(pay), round(avg(pay), 1)
  FROM (SELECT ROW_NUMBER() OVER (ORDER BY profno) AS num
             , profno, name, pay
		  FROM professor) inTbl
 GROUP BY ceil(intbl.Num/3), ROLLUP((inTbl.NUM, intbl.profno, intbl.name, intbl.pay))
 ORDER BY ceil(intbl.Num/3);


COMMIT;